### PR TITLE
Make changes to name and tag regexes, fix addmeeting response bug

### LINKED ISSUE #243: [PE-D][Tester C] Allows invalid email domains without periods
Input: add n/John p/11111111 e/johncom

Image

Allows emails with domains that are invalid, i.e. without a period separator. 
In real use cases, email domains without periods are invalid for sending and receiving external internet emails. A valid domain structure requires at least one period (e.g., example.com) to separate the domain name from the top-level domain (TLD).

Would be more useful to include this extra input validation condition, to ensure emails are valid.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #266: [PE-D][Tester E] Tags only allow alphanumeric characters and spaces
### Summary

The tag format only accepts alphanumeric characters and spaces. Tags such as `CS2103T-T12-3` are rejected.

### Why this is problematic

This prevents many natural, useful labels. Users have to invent awkward substitutes for common tag names.

### Steps to Reproduce

1. Launch the app.
2. Run `addtag 1 / CS2103T-T12-3`.

### Actual Results

The command fails because the tag format disallows those characters.

Image

### Expected Results

Tags should support a wider range of common label characters, or the restriction should be documented in the User Guide more clearly.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #272: [PE-D][Tester E] Name validation blocks some realistic names
### Summary

The name format only allows alphanumeric characters, spaces, forward slashes, commas, apostrophes, hyphens, and periods. Names containing parentheses, ampersands, `@`, or similar symbols are rejected.

### Why this is problematic

Some realistic names and labels cannot be entered as-is. Users have to distort saved names, which reduces accuracy.

### Steps to Reproduce

1. Launch the app.
2. Run `add n/Lawrence Wong (PM) p/91234567`.
3. Run `add n/Mr Tan @ Alex p/91234567`.

### Actual Results

Both commands fail because those characters are not accepted by the name validator.

Image

### Expected Results

The app should either support more realistic name formats or document the restrictions more clearly.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by darrenlhs**
Fixes #243, #261, #272

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java [hunk 1]
```diff
@@ -44,7 +44,7 @@ public AddMeetingCommand parse(String args) throws ParseException {
         Set<Index> indices = new HashSet<>();
         if (!areIndexesMissing) {
             indices = ParserUtil.parseIndices(argMultimap.getPreamble(),
-                    MEETING_TYPE, AddMeetingCommand.MESSAGE_USAGE);
+                    CONTACT_TYPE, AddMeetingCommand.MESSAGE_USAGE);
         }
```
Comment (Raylong268) [inline src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java:48]: LGTM

File: src/main/java/seedu/address/model/person/Email.java [hunk 2]
```diff
@@ -9,7 +9,7 @@
 public class Email {
 
     private static final String SPECIAL_CHARACTERS = "+_.-";
-    public static final String MESSAGE_CONSTRAINTS = "Emails should be of the format local-part@domain "
+    public static final String MESSAGE_CONSTRAINTS = "Emails should be of the format local-part@domain.com "
```
Comment (Raylong268) [inline src/main/java/seedu/address/model/person/Email.java]: Need to rephrase not .com since it can be any ending. old one was ok since domain already assumes .something, but maybe given an example so they know

File: src/main/java/seedu/address/model/person/Name.java [hunk 3]
```diff
@@ -10,14 +10,14 @@
...
                     + "It should not be blank, and it must start with an alphanumeric character.";
 
     /*
      * The first character of the address must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
      */
-    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} /,'.-]*";
+    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} \\p{Punct}]*";
 
     public final String fullName;
```
Comment (Raylong268) [inline src/main/java/seedu/address/model/person/Name.java:23]: lgtm

File: src/main/java/seedu/address/model/tag/Tag.java [hunk 4]
```diff
@@ -9,8 +9,10 @@
...
 public class Tag {
 
-    public static final String MESSAGE_CONSTRAINTS = "Tags names should be alphanumeric and may contain spaces";
-    public static final String VALIDATION_REGEX = "[\\p{Alnum} ]+";
+    public static final String MESSAGE_CONSTRAINTS =
+            "Tags names should be alphanumeric and may contain spaces "
+                    + "and special characters except for the forward slash { / }.";
+    public static final String VALIDATION_REGEX = "[\\p{Alnum} \\p{Punct}&&[^/]]+";
 
     public static final String STAR_TAG = "STAR";
```
Comment (Raylong268) [inline src/main/java/seedu/address/model/tag/Tag.java:18]: lgtm

**Review by Raylong268 — COMMENTED** [review]
Overall almost ok just a few small bugs

File: src/main/java/seedu/address/model/person/Email.java (hunk 2 above)
Comment (darrenlhs) [reply src/main/java/seedu/address/model/person/Email.java]: fixed, i made it say `local-part@domain` again, and added some text at the end to show examples of valid emails

**Review by Raylong268 — COMMENTED** [review]
LGTM
