### PR TITLE
Make code quality changes and fix message_usage in commands

### LINKED ISSUE #194: Amend message usage and overall code quality in repo

### PR DESCRIPTION
**Pull request by Raylong268**
Fixes #194

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditMeetingCommand.java [hunk 1]
```diff
@@ -29,28 +29,30 @@
...
+ * Edits the details of existing meetings in the meeting list.
  */
 public class EditMeetingCommand extends Command {
 
     public static final String COMMAND_WORD = "editmeeting";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Edits the details of the meeting identified "
-            + "by the index number used in the displayed meeting list.\n"
+    public static final String MESSAGE_USAGE = COMMAND_WORD
+            + ": Edits the details of the meeting identified by their index in the displayed meeting list.\n"
```
Comment (darrenlhs) [inline src/main/java/seedu/address/logic/commands/EditMeetingCommand.java]: small nitpick but for grammar, consider changing `their` to `its` cause it's not a person and its singular
