### PR TITLE
Make changes to EditMeetingCommandParser

### LINKED ISSUE #324: Editmeeting gives wrong index error hen no prefixes provided

### PR DESCRIPTION
**Pull request by darrenlhs**
Fixes #324

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java [hunk 1]
```diff
@@ -89,4 +92,24 @@ private EditMeetingDescriptor setEditMeetingDescriptor(ArgumentMultimap argMulti
...
+        boolean isDatePrefixMissing = !argMultimap.containsPrefix(PREFIX_MEETING_DATE);
+        boolean isAddIndicesPrefixMissing = !argMultimap.containsPrefix(PREFIX_ADD_CONTACT_TO_MEETING_INDEX);
+        boolean isDeleteIndicesPrefixMissing = !argMultimap.containsPrefix(PREFIX_DELETE_CONTACT_FROM_MEETING_INDEX);
+
+        if (isDescriptionPrefixMissing && isDatePrefixMissing
+                && isAddIndicesPrefixMissing && isDeleteIndicesPrefixMissing) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                    EditMeetingCommand.MESSAGE_USAGE));
+        }
+    }
```
Comment (Raylong268) [inline src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java:114]: LGTM

File: src/main/java/seedu/address/logic/parser/ArgumentMultimap.java [hunk 2]
```diff
@@ -75,4 +75,11 @@ public void verifyNoDuplicatePrefixesFor(Prefix... prefixes) throws ParseExcepti
...
         }
     }
+
+    /**
+     * Returns true if the given prefix appeared in the input, even if its value is empty.
+     */
+    public boolean containsPrefix(Prefix prefix) {
+        return argMultimap.containsKey(prefix);
+    }
 }
```
Comment (Raylong268) [inline src/main/java/seedu/address/logic/parser/ArgumentMultimap.java:85]: LGTM

**Review by Raylong268 — COMMENTED** [review]
LGTM can merge
