### PR TITLE
Fix/update meeting after edit person

### LINKED ISSUE #280: [PE-D][Tester B] Not updating automatically in meeting card after editing
Image

Image

Editing a person does not automatically update the meeting card views; I think it is still a bug, as we shouldn't expect user to click on the card one by one when they edit a person, this will affect the user experience.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by SpiritSK8**
Fixes #280 

Fixed by manually refreshing the meeting list view every time a change in the meeting list is detected.

The cause of the bug is probably because editing a person isn't registered as a "change" by the `ObservableList`. When editing a person, its ID stays the same, and since a `Meeting` only stores the IDs of the participants, it does not detect the change.

### CODE REVIEW

File: src/main/java/seedu/address/ui/meeting/MeetingListPanel.java [hunk 1]
```diff
@@ -61,6 +61,7 @@ private void buildListWithSeparators(ObservableList<Meeting> meetingList, Model
         }
 
         meetingListView.setItems(items);
+        meetingListView.refresh();
     }
```
Comment (Raylong268) [inline src/main/java/seedu/address/ui/meeting/MeetingListPanel.java:65]: LGTM

**Review by Raylong268 — COMMENTED** [review]
LGTM, going to ignore codecov since this file is UI
