### PR TITLE
Fix find command Null Pointer Exception

### LINKED ISSUE #121: Find function stops working if contact with a null variable is given
Need to fix find command, currently throws InvokationTargetException regardless of input if contact has a missing field of phone or email

### PR DESCRIPTION
**Pull request by yujiawang-0**
fix #121

### CODE REVIEW

File: src/main/java/seedu/address/model/person/PersonMatchesKeywordsPredicate.java [hunk 1]
```diff
@@ -33,8 +33,8 @@ public PersonMatchesKeywordsPredicate(List<String> globalKeywords,
     @Override
     public boolean test(Person person) {
         String name = person.getName().fullName.toLowerCase();
-        String phone = person.getPhone().value.toLowerCase();
-        String email = person.getEmail().value.toLowerCase();
+        String phone = person.getPhone() == null ? "" : person.getPhone().value.toLowerCase();
+        String email = person.getEmail() == null ? "" : person.getEmail().value.toLowerCase();
 
         // Global search
         if (!globalKeywords.isEmpty()) {
```
Comment (Raylong268) [inline src/main/java/seedu/address/model/person/PersonMatchesKeywordsPredicate.java]: LGTM

**Review by darrenlhs — COMMENTED** [review]
LGTM
