### PR TITLE
Fix/consistent filter reset

### LINKED ISSUE #264: [PE-D][Tester E] `edit` and `addtag` reset the filtered contact list, but `edittag`, `deletetag`, `star`, and `unstar` do not
### Summary

After running `edit` or `addtag`, the displayed contact list resets to show all contacts. However, `edittag`, `deletetag`, `star`, and `unstar` keep the current filter.

### Why this is problematic

Commands that use displayed indices should behave predictably. Inconsistent filter-reset behavior can confuse users and make follow-up commands riskier.

### Steps to Reproduce

1. Launch the app with sample data.
2. Run `find Alex`.
3. Observe the filtered list.
4. Run `addtag 1 / test`.
5. Observe that the list resets to show all contacts.
6. Run `find Alex` again.
7. Run `star 1`.
8. Observe that the list remains filtered.

### Actual Results

`addtag` clears the filter, but `star` does not.

Image
Image

### Expected Results

Similar modification commands should behave consistently, and the behavior should be documented.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by SpiritSK8**
Fixes #264 

Remove `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)` in `AddTagCommand` and `EditCommand`.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddTagCommand.java [hunk 1]
```diff
@@ -111,7 +110,6 @@ public CommandResult execute(Model model) throws CommandException {
             Person editedPerson = createPersonWithAddedTags(personToEdit, tags);
             model.setPerson(personToEdit, editedPerson);
         }
-        model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
 
         return new CommandResult(String.format(MESSAGE_ADD_TAG_SUCCESS, tags));
     }
```
Comment (Raylong268) [inline src/main/java/seedu/address/logic/commands/AddTagCommand.java:115]: LGTM

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -83,7 +82,6 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.setPerson(personToEdit, editedPerson);
-        model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
         return new CommandResult(String.format(MESSAGE_EDIT_PERSON_SUCCESS, Messages.format(editedPerson)));
     }
```
Comment (Raylong268) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:87]: LGTM

**Review by Raylong268 — COMMENTED** [review]
LGTM merging
