### PR TITLE
Fix the wrong error given when there are no prefixes (index error instead of command format)

### LINKED ISSUE #303: [PE-D][Tester B] Wrong error message for using invalid prefix in meeting page
Image

When I used n/ for meeting commands, it says invalid index even though the index is actually valid, and did not mention about the invalid prefix

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Raylong268**
Fixes #303

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindTagCommand.java [hunk 1]
```diff
@@ -38,7 +38,8 @@ public class FindTagCommand extends Command {
             "Found all people in the current list with at least one of these tag substrings (case-insensitive): %1$s"
             + "\n"
             + "%2$s persons listed!";
-    public static final String MESSAGE_NO_TAGS = "At least one tag substring must be provided." + "\n" + MESSAGE_FORMAT;
+    public static final String MESSAGE_NO_TAGS = "At least one non-empty "
+            + "tag substring must be provided." + "\n" + MESSAGE_FORMAT;
```
Comment (SpiritSK8) [inline src/main/java/seedu/address/logic/commands/FindTagCommand.java:42]: I think you can combine this into a single line without + between "At least one non-empty " and "tag substring must be provided."

**Review by SpiritSK8 — COMMENTED** [review]
Just a minor line break issue and checkstyle violation! Besides that it LGTM.

File: src/main/java/seedu/address/logic/commands/FindTagCommand.java (hunk 1 above)
Comment (Raylong268) [reply src/main/java/seedu/address/logic/commands/FindTagCommand.java:42]: Cannot do that since it will exceed the text count for that line unfort, but thx for the feedback!
