### PR TITLE
Fix/global find prefix

### LINKED ISSUE #256: [PE-D][Tester E] Global `find` rejects valid search strings that contain `n/`, `p/`, or `e/`
### Summary

The app allows names containing `/`, but global `find` misclassifies ordinary search text as prefixed input whenever the search term contains `n/`, `p/`, or `e/` anywhere inside it.

### Steps to Reproduce

1. Add a contact with a slash-containing name, for example: `add n/Aaron/Tan p/91234567`.
2. Run `find Aaron/Tan`.

### Actual Results

Fails with `Cannot mix global search with prefixed search.` even though the input is a plain global search string.

Image

### Expected Results

The command should treat `Aaron/Tan` as a normal global search term and return matching contacts.

### Why this is problematic

It prevents users from searching for legitimate text that happens to contain those character sequences. Since slash-containing names are accepted by the app, users can create data that they later cannot reliably search for using the documented global `find` behavior.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by SpiritSK8**
Fixes #256 

Changed the logic of checking for mixed global and prefix search to use the argument multimap instead of `String::contains()`.

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -16,6 +16,7 @@ public class Messages {
     public static final String MESSAGE_INVALID_COMMAND_FORMAT = "Invalid command format! \n%1$s";
     public static final String MESSAGE_BLANK_FIND_FIELD_INPUT = "Input for find fields cannot be empty! \n%1$s";
     public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX = "The person index provided is invalid";
+    public static final String MESSAGE_MIX_GLOBAL_AND_PREFIX_SEARCH = "Cannot mix global search with prefixed search.";
     public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d persons listed!";
     public static final String MESSAGE_MEETINGS_LISTED_OVERVIEW = "%1$d meetings listed!";
     public static final String MESSAGE_DUPLICATE_FIELDS =
```
Comment (Raylong268) [inline src/main/java/seedu/address/logic/Messages.java:22]: LGTM

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 2]
```diff
@@ -49,26 +50,25 @@ public FindCommand parse(String args) throws ParseException {
...
+        boolean hasEmailPrefix = !emailKeywords.isEmpty();
 
         boolean hasAnyPrefixedSearch = hasNamePrefix || hasPhonePrefix || hasEmailPrefix;
 
         if (!preamble.isEmpty() && hasAnyPrefixedSearch) {
-            throw new ParseException("Cannot mix global search with prefixed search.");
+            throw new ParseException(Messages.MESSAGE_MIX_GLOBAL_AND_PREFIX_SEARCH);
         }
 
         validateFieldInput(hasNamePrefix, nameKeywords);
```
Comment (Raylong268) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:74]: LGTM

**Review by Raylong268 — COMMENTED** [review]
LGTM, merging
